# Snipe-IT Docker tasks - main.yml
---
- name: create nginx proxy container
  docker_container:
    name: nginx-proxy
    image: "jwilder/nginx-proxy:{{ nginx_proxy_version }}"
    state: started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/docker:/etc/nginx/certs
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem

- name: create snipe-it directory
  file:
    path: "{{ snipeit_directory }}/{{ item }}"
    mode: 0700
    state: directory
  with_items:
    -
    - mysql
    - data

- name: create snipeit env file
  template:
    src: env.j2
    dest: "{{ snipeit_directory }}/.env"
    mode: 0600

- name: create snipe-it database
  docker_container:
    name: snipeit-mysql
    image: "mysql:{{ snipeit_mysql_version }}"
    state: started
    env_file: "{{ snipeit_directory }}/.env"
    volumes:
      - "{{ snipeit_directory }}/mysql:/var/lib/mysql:rw"

- name: create snipe-it container
  docker_container:
    name: snipeit
    image: "snipe/snipe-it:{{ snipeit_version }}"
    state: started
    exposed_ports:
      - 80
    env_file: "{{ snipeit_directory }}/.env"
    env:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: "{{ snipeit_domain_name }}"
    volumes:
      - "{{ snipeit_directory }}/data:/var/lib/snipeit"
    links:
      - snipeit-mysql:mysql
   register: snipeit_container

- name: allow snipe-it database to initialize
  pause:
    seconds: 60
  when: snipeit_database.changed and
        snipeit_container.change

- name: migrate snipe-it database
  command: docker exec -t snipeit php artisan migrate --force
  when: snipeit_container.changed
